#development:
#  adapter: sqlite3
#  encoding: unicode
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database: wisdoms_development
  username: wisdoms
  password: wisdomspassword
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: wisdoms_test
  username: wisdoms
  password: wisdomspassword
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: wisdoms_production
  username: wisdoms
  password: wisdomspassword
