#development:
#  adapter: sqlite3
#  encoding: unicode
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database: wisdoms_development
  pool: 5
  username: myapp
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: wisdoms_test
  pool: 5
  username: myapp
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: wisdoms_production
  pool: 5
  username: myapp
  password:
