#development:
#  adapter: sqlite3
#  encoding: unicode
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database: wisdoms_development
  username: vagrant
  password: vagrant
  host: localhost
  template: template0
test:
  adapter: postgresql
  encoding: unicode
  database: wisdoms_test
  username: vagrant
  password: vagrant
  host: localhost
  template: template0
production:
  adapter: postgresql
  encoding: unicode
  database: wisdoms_production
  username: vagrant
  password: vagrant
  template: template0
